replicaCount: 1

image:
  tag: "dev"

env:
  - name: LOG_LEVEL
    value: debug
  - name: FEATURE_FLAG
    value: "true"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
